site_name: SemanticWeb
site_author: "Vu Anh"
google_analytics: ["UA-68978617-1", "magizbox.com"]

pages:
- "<span class='fa fa-home'></span> Home": "index.md"
- "<span class='fa fa-book'></span> Learn":
  - "Web 3.0": "web_3_0.md"
  - "RDF": "rdf.md"
  - "SPARQL": "sparql.md"
- "<span class='fa fa-question-circle'></span> Ask": "ask.md"

markdown_extensions:
    - footnotes

extra_css:
  - components/magiz-c-book/src/book.css
  - components/magiz-c-course/src/course.css
  - components/magiz-c-video/src/video.css
  - components/magiz-c-benchmark/src/benchmark.css
  - components/magiz-c-paper/src/paper.css

extra_javascript:
  - components/underscore/underscore.js
  - components/magiz-c-book/src/gspreadsheet.js
  - components/magiz-c-paper/src/paper.js
  - components/magiz-c-course/src/course.js
  - components/magiz-c-benchmark/src/benchmark.js
  - components/magiz-c-benchmark/src/bootstrap-popup.js
  - components/magiz-c-book/src/book.js
  - components/magiz-c-video/src/video.js

